
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'te' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    title: "DigiPanchayath",
    subtitle: "Digital Governance Platform",
    reportIssue: "Report Issue",
    trackProgress: "Track Progress",
    schemes: "Schemes",
    escalate: "Escalate",
    backToHome: "Back to Home",
    backToSchemes: "Back to Schemes",
    officerLogin: "Officer Login",
    submitReport: "Submit Report",
    trackStatus: "Track Status",
    viewSchemes: "View Schemes",
    escalateIssue: "Escalate Issue",
    myReports: "My Reports",
    // Report Issue Page
    reportIssueTitle: "Report Issue",
    reportIssueSubtitle: "Submit your complaint for quick resolution",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    enterFullName: "Enter your full name",
    mobileNumber: "Mobile Number",
    enterMobileNumber: "Enter your mobile number",
    emailAddress: "Email Address",
    enterEmailAddress: "Enter your email address",
    sendOTP: "Send OTP",
    verified: "Verified",
    emailVerificationCode: "Email Verification Code",
    enterVerificationCode: "Enter 6-digit code",
    verify: "Verify",
    issueDetails: "Issue Details",
    selectDistrict: "Select District",
    selectVillage: "Select Village",
    selectIssueType: "Select Issue Type",
    issueDescription: "Issue Description",
    describeIssue: "Describe your issue in detail...",
    priority: "Priority",
    low: "Low",
    medium: "Medium",
    high: "High",
    uploadEvidence: "Upload Evidence",
    takePhoto: "Take Photo",
    photoCaptured: "Photo Captured ✓",
    chooseFiles: "Choose Files",
    uploadPhotos: "Photos, videos, or documents (Max 5MB each)",
    cancel: "Cancel",
    // Escalate Page
    escalateComplaint: "Escalate Complaint",
    escalateSubtitle: "File escalation for unresolved issues",
    originalComplaintId: "Original Complaint ID",
    enterComplaintId: "Enter your complaint ID (e.g., TG001)",
    reasonForEscalation: "Reason for Escalation",
    selectEscalationReason: "Select reason for escalation",
    escalateTo: "Escalate To",
    selectEscalationLevel: "Select escalation level",
    additionalDetails: "Additional Details",
    provideContext: "Provide additional context for escalation...",
    supportingEvidence: "Supporting Evidence",
    uploadDocuments: "Upload additional documents",
    submitEscalation: "Submit Escalation",
    // Officer Dashboard
    officerDashboard: "Officer Dashboard",
    governmentPortal: "DigiPanchayath - Government Portal",
    totalComplaints: "Total Complaints",
    pending: "Pending",
    inProgress: "In Progress",
    completed: "Completed",
    districtWiseHeatMap: "District-wise Complaint Heat Map (Your Department)",
    yourDepartmentComplaints: "Your Department Complaints",
    filterByDistrict: "Filter by District",
    allDistricts: "All Districts",
    complaintId: "Complaint ID",
    district: "District",
    village: "Village",
    issueType: "Issue Type",
    status: "Status",
    priorityLabel: "Priority",
    action: "Action",
    viewDetails: "View Details",
    logout: "Logout",
    // Schemes Page
    schemesTitle: "Government Schemes",
    schemesSubtitle: "Explore available government schemes and benefits",
    searchSchemes: "Search schemes...",
    filterByCategory: "Filter by Category",
    allCategories: "All Categories",
    active: "Active",
    viewDetailsButton: "View Details",
    applyNow: "Apply Now",
    close: "Close",
    // Messages
    emailRequired: "Email Required",
    enterEmailFirst: "Please enter your email address first.",
    otpSent: "OTP Sent",
    verificationCodeSent: "Verification code sent to",
    checkEmail: "Please check your email.",
    emailVerified: "Email Verified",
    emailVerifiedSuccess: "Your email has been successfully verified.",
    invalidOTP: "Invalid OTP",
    enterCorrectCode: "Please enter the correct verification code.",
    photoCapturedSuccess: "Photo has been successfully captured and uploaded.",
    escalationSubmitted: "Escalation Submitted",
    escalationSubmittedSuccess: "Your escalation has been submitted successfully.",
    reportSubmitted: "Report Submitted",
    reportSubmittedSuccess: "Your report has been submitted successfully.",
    emailNotVerified: "Email Not Verified",
    verifyEmailFirst: "Please verify your email address before submitting.",
  },
  te: {
    title: "డిజిపంచాయతి",
    subtitle: "డిజిటల్ పాలన వేదిక",
    reportIssue: "సమస్యను నివేదించండి",
    trackProgress: "పురోగతిని ట్రాక్ చేయండి",
    schemes: "పథకాలు",
    escalate: "ఎస్కలేట్ చేయండి",
    backToHome: "హోమ్‌కు తిరిగి వెళ్లండి",
    backToSchemes: "పథకాలకు తిరిగి వెళ్లండి",
    officerLogin: "అధికారి లాగిన్",
    submitReport: "నివేదిక సమర్పించండి",
    trackStatus: "స్థితిని ట్రాక్ చేయండి",
    viewSchemes: "పథకాలను చూడండి",
    escalateIssue: "సమస్యను ఎస్కలేట్ చేయండి",
    myReports: "నా నివేదికలు",
    // Report Issue Page
    reportIssueTitle: "సమస్యను నివేదించండి",
    reportIssueSubtitle: "త్వరిత పరిష్కారం కోసం మీ ఫిర్యాదును సమర్పించండి",
    personalInfo: "వ్యక్తిగత సమాచారం",
    fullName: "పూర్తి పేరు",
    enterFullName: "మీ పూర్తి పేరును నమోదు చేయండి",
    mobileNumber: "మొబైల్ నంబర్",
    enterMobileNumber: "మీ మొబైల్ నంబర్‌ను నమోదు చేయండి",
    emailAddress: "ఇమెయిల్ చిరునామా",
    enterEmailAddress: "మీ ఇమెయిల్ చిరునామాను నమోదు చేయండి",
    sendOTP: "OTP పంపండి",
    verified: "ధృవీకరించబడింది",
    emailVerificationCode: "ఇమెయిల్ ధృవీకరణ కోడ్",
    enterVerificationCode: "6-అంకెల కోడ్‌ను నమోదు చేయండి",
    verify: "ధృవీకరించండి",
    issueDetails: "సమస్య వివరాలు",
    selectDistrict: "జిల్లాను ఎంచుకోండి",
    selectVillage: "గ్రామాన్ని ఎంచుకోండి",
    selectIssueType: "సమస్య రకాన్ని ఎంచుకోండి",
    issueDescription: "సమస్య వివరణ",
    describeIssue: "మీ సమస్యను వివరంగా వర్ణించండి...",
    priority: "ప్రాధాన్యత",
    low: "తక్కువ",
    medium: "మధ్యస్థ",
    high: "అధిక",
    uploadEvidence: "సాక్ష్యం అప్‌లోడ్ చేయండి",
    takePhoto: "ఫోటో తీయండి",
    photoCaptured: "ఫోటో తీయబడింది ✓",
    chooseFiles: "ఫైల్‌లను ఎంచుకోండి",
    uploadPhotos: "ఫోటోలు, వీడియోలు లేదా డాక్యుమెంట్‌లు (గరిష్టంగా 5MB ప్రతి)",
    cancel: "రద్దు చేయండి",
    // Escalate Page
    escalateComplaint: "ఫిర్యాదును ఎస్కలేట్ చేయండి",
    escalateSubtitle: "పరిష్కరించని సమస్యల కోసం ఎస్కలేషన్ దాఖలు చేయండి",
    originalComplaintId: "అసలు ఫిర్యాదు ID",
    enterComplaintId: "మీ ఫిర్యాదు IDను నమోదు చేయండి (ఉదా: TG001)",
    reasonForEscalation: "ఎస్కలేషన్‌కు కారణం",
    selectEscalationReason: "ఎస్కలేషన్ కారణాన్ని ఎంచుకోండి",
    escalateTo: "ఎవరికి ఎస్కలేట్ చేయాలి",
    selectEscalationLevel: "ఎస్కలేషన్ స్థాయిని ఎంచుకోండి",
    additionalDetails: "అదనపు వివరాలు",
    provideContext: "ఎస్కలేషన్ కోసం అదనపు సందర్భాన్ని అందించండి...",
    supportingEvidence: "సహాయక సాక్ష్యం",
    uploadDocuments: "అదనపు డాక్యుమెంట్‌లను అప్‌లోడ్ చేయండి",
    submitEscalation: "ఎస్కలేషన్ సమర్పించండి",
    // Officer Dashboard
    officerDashboard: "అధికారి డాష్‌బోర్డ్",
    governmentPortal: "డిజిపంచాయతి - ప్రభుత్వ పోర్టల్",
    totalComplaints: "మొత్తం ఫిర్యాదులు",
    pending: "పెండింగ్‌లో",
    inProgress: "ప్రగతిలో",
    completed: "పూర్తయింది",
    districtWiseHeatMap: "జిల్లావారీ ఫిర్యాదుల హీట్ మ్యాప్ (మీ డిపార్ట్‌మెంట్)",
    yourDepartmentComplaints: "మీ డిపార్ట్‌మెంట్ ఫిర్యాదులు",
    filterByDistrict: "జిల్లా ద్వారా ఫిల్టర్ చేయండి",
    allDistricts: "అన్ని జిల్లాలు",
    complaintId: "ఫిర్యాదు ID",
    district: "జిల్లా",
    village: "గ్రామం",
    issueType: "సమస్య రకం",
    status: "స్థితి",
    priorityLabel: "ప్రాధాన్యత",
    action: "చర్య",
    viewDetails: "వివరాలు చూడండి",
    logout: "లాగ్‌అవుట్",
    // Schemes Page
    schemesTitle: "ప్రభుత్వ పథకాలు",
    schemesSubtitle: "అందుబాటులో ఉన్న ప్రభుత్వ పథకాలు మరియు ప్రయోజనాలను అన్వేషించండి",
    searchSchemes: "పథకాలను వెతకండి...",
    filterByCategory: "వర్గం ద్వారా ఫిల్టర్ చేయండి",
    allCategories: "అన్ని వర్గాలు",
    active: "క్రియాశీల",
    viewDetailsButton: "వివరాలు చూడండి",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    close: "మూసివేయండి",
    // Messages
    emailRequired: "ఇమెయిల్ అవసరం",
    enterEmailFirst: "దయచేసి మొదట మీ ఇమెయిల్ చిరునామాను నమోదు చేయండి.",
    otpSent: "OTP పంపబడింది",
    verificationCodeSent: "ధృవీకరణ కోడ్ పంపబడింది",
    checkEmail: "దయచేసి మీ ఇమెయిల్‌ను తనిఖీ చేయండి.",
    emailVerified: "ఇమెయిల్ ధృవీకరించబడింది",
    emailVerifiedSuccess: "మీ ఇమెయిల్ విజయవంతంగా ధృవీకరించబడింది.",
    invalidOTP: "చెల్లని OTP",
    enterCorrectCode: "దయచేసి సరైన ధృవీకరణ కోడ్‌ను నమోదు చేయండి.",
    photoCapturedSuccess: "ఫోటో విజయవంతంగా క్యాప్చర్ చేయబడింది మరియు అప్‌లోడ్ చేయబడింది.",
    escalationSubmitted: "ఎస్కలేషన్ సమర్పించబడింది",
    escalationSubmittedSuccess: "మీ ఎస్కలేషన్ విజయవంతంగా సమర్పించబడింది.",
    reportSubmitted: "నివేదిక సమర్పించబడింది",
    reportSubmittedSuccess: "మీ నివేదిక విజయవంతంగా సమర్పించబడింది.",
    emailNotVerified: "ఇమెయిల్ ధృవీకరించబడలేదు",
    verifyEmailFirst: "దయచేసి సమర్పించే ముందు మీ ఇమెయిల్ చిరునామాను ధృవీకరించండి.",
  },
  hi: {
    title: "डिजिपंचायत",
    subtitle: "डिजिटल शासन मंच",
    reportIssue: "समस्या रिपोर्ट करें",
    trackProgress: "प्रगति ट्रैक करें",
    schemes: "योजनाएं",
    escalate: "एस्केलेट करें",
    backToHome: "होम पर वापस जाएं",
    backToSchemes: "योजनाओं पर वापस जाएं",
    officerLogin: "अधिकारी लॉगिन",
    submitReport: "रिपोर्ट सबमिट करें",
    trackStatus: "स्थिति ट्रैक करें",
    viewSchemes: "योजनाएं देखें",
    escalateIssue: "समस्या एस्केलेट करें",
    myReports: "मेरी रिपोर्ट्स",
    // Report Issue Page
    reportIssueTitle: "समस्या रिपोर्ट करें",
    reportIssueSubtitle: "त्वरित समाधान के लिए अपनी शिकायत दर्ज करें",
    personalInfo: "व्यक्तिगत जानकारी",
    fullName: "पूरा नाम",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    mobileNumber: "मोबाइल नंबर",
    enterMobileNumber: "अपना मोबाइल नंबर दर्ज करें",
    emailAddress: "ईमेल पता",
    enterEmailAddress: "अपना ईमेल पता दर्ज करें",
    sendOTP: "OTP भेजें",
    verified: "सत्यापित",
    emailVerificationCode: "ईमेल सत्यापन कोड",
    enterVerificationCode: "6-अंकीय कोड दर्ज करें",
    verify: "सत्यापित करें",
    issueDetails: "समस्या विवरण",
    selectDistrict: "जिला चुनें",
    selectVillage: "गांव चुनें",
    selectIssueType: "समस्या का प्रकार चुनें",
    issueDescription: "समस्या का विवरण",
    describeIssue: "अपनी समस्या का विस्तार से वर्णन करें...",
    priority: "प्राथमिकता",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    uploadEvidence: "सबूत अपलोड करें",
    takePhoto: "फोटो लें",
    photoCaptured: "फोटो कैप्चर किया गया ✓",
    chooseFiles: "फाइलें चुनें",
    uploadPhotos: "फोटो, वीडियो या दस्तावेज (अधिकतम 5MB प्रत्येक)",
    cancel: "रद्द करें",
    // Escalate Page
    escalateComplaint: "शिकायत एस्केलेट करें",
    escalateSubtitle: "अनसुलझी समस्याओं के लिए एस्केलेशन दाखिल करें",
    originalComplaintId: "मूल शिकायत ID",
    enterComplaintId: "अपनी शिकायत ID दर्ज करें (जैसे: TG001)",
    reasonForEscalation: "एस्केलेशन का कारण",
    selectEscalationReason: "एस्केलेशन का कारण चुनें",
    escalateTo: "कहां एस्केलेट करें",
    selectEscalationLevel: "एस्केलेशन स्तर चुनें",
    additionalDetails: "अतिरिक्त विवरण",
    provideContext: "एस्केलेशन के लिए अतिरिक्त संदर्भ प्रदान करें...",
    supportingEvidence: "सहायक सबूत",
    uploadDocuments: "अतिरिक्त दस्तावेज अपलोड करें",
    submitEscalation: "एस्केलेशन सबमिट करें",
    // Officer Dashboard
    officerDashboard: "अधिकारी डैशबोर्ड",
    governmentPortal: "डिजिपंचायत - सरकारी पोर्टल",
    totalComplaints: "कुल शिकायतें",
    pending: "लंबित",
    inProgress: "प्रगति में",
    completed: "पूर्ण",
    districtWiseHeatMap: "जिलेवार शिकायत हीट मैप (आपका विभाग)",
    yourDepartmentComplaints: "आपके विभाग की शिकायतें",
    filterByDistrict: "जिले के अनुसार फ़िल्टर करें",
    allDistricts: "सभी जिले",
    complaintId: "शिकायत ID",
    district: "जिला",
    village: "गांव",
    issueType: "समस्या का प्रकार",
    status: "स्थिति",
    priorityLabel: "प्राथमिकता",
    action: "कार्रवाई",
    viewDetails: "विवरण देखें",
    logout: "लॉगआउट",
    // Schemes Page
    schemesTitle: "सरकारी योजनाएं",
    schemesSubtitle: "उपलब्ध सरकारी योजनाओं और लाभों का अन्वेषण करें",
    searchSchemes: "योजनाएं खोजें...",
    filterByCategory: "श्रेणी के अनुसार फ़िल्टर करें",
    allCategories: "सभी श्रेणियां",
    active: "सक्रिय",
    viewDetailsButton: "विवरण देखें",
    applyNow: "अभी आवेदन करें",
    close: "बंद करें",
    // Messages
    emailRequired: "ईमेल आवश्यक",
    enterEmailFirst: "कृपया पहले अपना ईमेल पता दर्ज करें।",
    otpSent: "OTP भेजा गया",
    verificationCodeSent: "सत्यापन कोड भेजा गया",
    checkEmail: "कृपया अपना ईमेल चेक करें।",
    emailVerified: "ईमेल सत्यापित",
    emailVerifiedSuccess: "आपका ईमेल सफलतापूर्वक सत्यापित हो गया है।",
    invalidOTP: "अवैध OTP",
    enterCorrectCode: "कृपया सही सत्यापन कोड दर्ज करें।",
    photoCapturedSuccess: "फोटो सफलतापूर्वक कैप्चर और अपलोड किया गया है।",
    escalationSubmitted: "एस्केलेशन सबमिट किया गया",
    escalationSubmittedSuccess: "आपका एस्केलेशन सफलतापूर्वक सबमिट किया गया है।",
    reportSubmitted: "रिपोर्ट सबमिट की गई",
    reportSubmittedSuccess: "आपकी रिपोर्ट सफलतापूर्वक सबमिट की गई है।",
    emailNotVerified: "ईमेल सत्यापित नहीं",
    verifyEmailFirst: "कृपया सबमिट करने से पहले अपना ईमेल पता सत्यापित करें।",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
