// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtjgqfbsravharjyestz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10amdxZmJzcmF2aGFyanllc3R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjU1NjcsImV4cCI6MjA2NTY0MTU2N30.T1P7fvcEEkIvow0syW8e7XhxjYsybxH4O40IbX3Earg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);